### ISSUE TITLE
Cannot open a template

### ISSUE THREAD

**Issue by Lucretia** [rehartmann/JinTP#3]
I've got an alr test project:

```ada
with Ada.Directories;
with Ada.Text_IO;
with JinTP;

procedure Testj is
   package IO renames Ada.Text_IO;

   D : JinTP.Dictionary;
begin
   IO.Put_Line ("CWD: " & Ada.Directories.Current_Directory);
   IO.Put_Line (Jintp.Render ("./src/templates/test.ads.jinja", D));
end Testj;
```

Where the CWD = "<path-to>/testj".

But it constantly fails with: `raised JINTP.TEMPLATE_ERROR : template not found: ./src/templates/test.ads.jinja`

I've tried with the `./` and without it, I've tried appending the CWD instead of it, it fails every time.

What am I missing here?

**Comment by Lucretia** [comment]
In GDB it's failing here:

```
Catchpoint 1, CONSTRAINT_ERROR (bad input for 'Value: "PACKAGE_TOKEN") at 0x000000000040aba3 in jintp.scanner.to_token (source=..., result=..., 
    <resultO>=<resultO>@entry=false)
    at /home/laguest/.local/share/alire/builds/jintp_0.1.0_92c90075/4c5a44ee36b6d42e76f46abdc7fe1d3c04d8a5c2c88f23b5fa3cbadbd825920f/src/jintp-scanner.adb:24
24               Tok_Kind : constant Symbolic_Token_Kind := Symbolic_Token_Kind'Value
```

Can your templates only handle html??

**Comment by Lucretia** [comment]
I tried the latest git as well, same error.

test.ads.jinja:

```jinja
{% include 'packages.jinja' %}

{{ package('Test') }}
```

and packages.jinja:

```jinja
{% macro package(name, value='--  TODO: Text.') %}
package {{ name }} is
   {{ text }}
end {{ name }};
{% endmacro %}
```

**Comment by rehartmann** [comment]
The error message is misleading. It is actually packages.jinja which is not found because when an include file is read the same base directory is used as when reading the parent.
The following include works:
`{% include './src/templates/packages.jinja' %}`

Unfortunately it overall still fails because expanding a macro from an included template does not work yet. I am working on this.

**Comment by rehartmann** [comment]
At least the error message is now fixed.

**Comment by Lucretia** [comment]
The that doesn't work the same way Jinja2 does. I've tested it with jinja2-cli and it works.

I'll be using that to test to see if this can do what I need it to, but I'd prefer something I could link to rather than spawn.

**Comment by Lucretia** [comment]
I see that is dependent:

>You can access templates in subdirectories with a slash:
>
>{% extends "layout/default.html" %}
>
>But this behavior can depend on the application embedding Jinja.

**Comment by rehartmann** [comment]
I tried it with Jinja2 and got an error "'package' is undefined". Maybe it depends on the version?
Anyway, I think supporting import is the cleaner approach so I will see if I can get this implemented.

**Comment by Lucretia** [comment]
Look at what [jinja2-cli](https://github.com/mattrobenolt/jinja2-cli) does as that is what I'm using here.

**Comment by rehartmann** [comment]
Expanding macros from included files is now supported.

**Comment by Lucretia** [comment]
Thanks, but it still needs the "with context" part adding so you can pass the dictionary to imported templates.

**Comment by rehartmann** [comment]
That's not a problem with include but with the implementation of macros. I am considering a redesign of the context implementation.

**Comment by rehartmann** [comment]
Accessing variables from included macros works now.

**Comment by rehartmann** [comment]
Issue is fixed.

**Comment by Lucretia** [comment]
Does it work with import too or just include?

**Comment by rehartmann** [comment]
No, import is not implemented yet.
