### ISSUE TITLE
Request: Import

### ISSUE THREAD

**Issue by Lucretia** [rehartmann/JinTP#4]
Having the import as functionality would be useful, I intend on using this for a largish project.

**Comment by Lucretia** [comment]
Seems this is required to get macros to work according to the jinja docs.

> If the macro was defined in a different template, you have to [import](https://jinja.palletsprojects.com/en/stable/templates/#import) it first.

I need this functionality for a project. I just found out why my jinja2-cli test didn't work, it needs the "with context" part of the import, which you would also need to implement to get it to pass on the environment to the macros, which is what I need.

**Comment by rehartmann** [comment]
Import is now supported. The support is limited to `import <filename> as <variable>`.
`From <filename> import ...` is not supported (yet).

**Comment by rehartmann** [comment]
From <filename> import ... is now supported.
